apiVersion: v1
kind: Service
metadata:
  name: magicalroleapi-service
spec:
  selector:
    app: magicalroleapi
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080